@startuml
' Définition du style pour une meilleure lisibilité
skinparam actorStyle awesome
skinparam usecase {
    BackgroundColor #LightGreen
    BorderColor #DarkGreen
    ArrowColor #Navy
}
skinparam package {
    BackgroundColor #lightblue
    BorderColor #blue
}

left to right direction

' Définition des acteurs
actor "Utilisateur" as PC
actor "MyRIO" as MyRIO

' Définition du système d'ascenseur (Cas d'utilisation Niv 2)
rectangle "Système de Gestion d'Ascenseur - Niv 2" {
    usecase "Poussoir appel descente niv 2" as UC4
    usecase "Voyant appel descente niv 2" as UC4_1
    usecase "Poussoir appel montée niv 2" as UC5
    usecase "Voyant appel montée niv 2" as UC5_1
    usecase "Voyant présence cabine niv 2" as UCCabAtNiv2
    usecase "Moteur Ouverture porte niv 2" as UC4_2
    usecase "Moteur Fermeture porte niv 2" as UC4_3
}

' Relations entre les acteurs et les cas d'utilisation
PC --> UC4 : Appuie sur le poussoir (Descente)
MyRIO --> UC4_1 : Allume le voyant (Descente)
PC --> UC5 : Appuie sur le poussoir (Montée)
MyRIO --> UC5_1 : Allume le voyant (Montée)

MyRIO --> UCCabAtNiv2 : Recois la position cabine
MyRIO --> UC4_2 : Active le moteur ouverture porte
MyRIO --> UC4_3 : Active le moteur fermeture porte

' Relations d'inclusion
UC4_1 ..> UC4 : <<include>>
UC5_1 ..> UC5 : <<include>>
@enduml